version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./uploads:/app/uploads
    environment:
      - ENV=development
      - DEBUG=true
      - GROQ_AI_API_KEY=${GROQ_AI_API_KEY}
      - UPLOAD_DIRECTORY=uploads
      - MAX_FILE_SIZE=10485760
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:8000
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload


volumes:
  uploads: